# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [8.12.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install -g cnpm --registry=https://registry.npm.taobao.org && cnpm install && npm run build

    - name: push
      run: |
        cd gh-pages
        git init
        git config user.name "hank.qin1994"
        git config user.email "hank.qin1994@gmail.com"
        git add .
        git commit -m "Update docs"
        git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GH_REF: github.com/Qinhank/win_necessary_soft.git
